root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/api/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "html", "toml"]
  exclude_regex = ["_test.go"]
  log = "build-errors.log"

[log]
  time = true
